/**
 * Route Generator Script
 * 
 * This script scans the /app directory for all page.tsx files
 * and automatically generates:
 * - lib/routes.ts (canonical route registry)
 * - URL.md (route documentation)
 * 
 * Usage:
 * npx tsx scripts/generate-routes.ts
 * 
 * Add to package.json scripts:
 * "generate-routes": "npx tsx scripts/generate-routes.ts"
 */

import fs from 'fs'
import path from 'path'

const APP_DIR = path.join(process.cwd(), 'app')
const OUTPUT_ROUTES = path.join(process.cwd(), 'lib', 'routes.ts')
const OUTPUT_URL_MD = path.join(process.cwd(), 'URL.md')

// Files to ignore
const IGNORE_FILES = ['layout.tsx', 'loading.tsx', 'error.tsx', 'global-error.tsx']

interface RouteInfo {
  path: string
  name: string
  category: string
}

// Convert file path to URL path
function filePathToUrlPath(filePath: string): string {
  // Remove 'app' prefix and 'page.tsx' suffix
  let urlPath = filePath
    .replace(/^app/, '')
    .replace(/\/page\.tsx$/, '')
    .replace(/\\/g, '/')
  
  // Handle dynamic routes [slug] -> :slug
  urlPath = urlPath.replace(/\[([^\]]+)\]/g, ':$1')
  
  // Handle root page
  if (urlPath === '') {
    return '/'
  }
  
  return urlPath
}

// Convert path segment to readable name
function pathToName(segment: string): string {
  // Handle dynamic routes
  if (segment.startsWith(':')) {
    return segment.slice(1).charAt(0).toUpperCase() + segment.slice(2)
  }
  
  return segment
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

// Determine route category
function getCategory(filePath: string): string {
  const lowerPath = filePath.toLowerCase()
  
  if (lowerPath.includes('company')) return 'company'
  if (lowerPath.includes('platform')) return 'platform'
  if (lowerPath.includes('industries')) return 'industries'
  if (lowerPath.includes('solutions')) return 'solutions'
  if (lowerPath.includes('products')) return 'products'
  if (lowerPath.includes('resources')) return 'resources'
  if (lowerPath.includes('blog')) return 'blog'
  if (lowerPath.includes('case-studies')) return 'case-studies'
  if (lowerPath.includes('privacy') || lowerPath.includes('terms')) return 'legal'
  
  return 'core'
}

// Scan directory recursively
function scanDirectory(dir: string, basePath: string = ''): string[] {
  const routes: string[] = []
  
  if (!fs.existsSync(dir)) {
    return routes
  }
  
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    const relativePath = path.join(basePath, entry.name)
    
    if (entry.isDirectory()) {
      // Skip directories that don't contain page.tsx at root level
      const pagePath = path.join(fullPath, 'page.tsx')
      if (fs.existsSync(pagePath)) {
        routes.push(relativePath)
      }
      // Recursively scan subdirectories
      routes.push(...scanDirectory(fullPath, relativePath))
    }
  }
  
  return routes
}

// Find all page.tsx files
function findAllPages(dir: string): string[] {
  const pages: string[] = []
  
  function walk(currentDir: string) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true })
    
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name)
      
      if (entry.isDirectory()) {
        // Check if this directory has a page.tsx
        const pagePath = path.join(fullPath, 'page.tsx')
        if (fs.existsSync(pagePath) && !IGNORE_FILES.includes(entry.name)) {
          pages.push(fullPath)
        }
        // Continue walking
        walk(fullPath)
      }
    }
  }
  
  walk(dir)
  return pages
}

// Generate routes.ts content
function generateRoutesTs(routes: RouteInfo[]): string {
  const staticRoutes = routes
    .filter(r => !r.path.includes(':'))
    .map(r => `  { path: '${r.path}', name: '${r.name}', category: '${r.category}' }`)
    .join(',\n')
  
  return `/**
 * Kritvia Route Registry
 * 
 * This file acts as the canonical registry of every route in the platform.
 * All systems must reference this registry for route information.
 * 
 * IMPORTANT: When a new page is added, removed, or renamed in the \`/app\` directory,
 * this file must be updated immediately.
 * 
 * Auto-generated by scripts/generate-routes.ts
 */

export interface Route {
  path: string
  name: string
  category: 'core' | 'company' | 'products' | 'solutions' | 'industries' | 'platform' | 'resources' | 'legal'
  description?: string
}

export const routes: Route[] = [
${staticRoutes},
]

// Static routes for sitemap
export const staticRoutes = [
${routes.filter(r => !r.path.includes(':')).map(r => `  '${r.path}'`).join(',\n')}
]

// Dynamic route patterns
export const dynamicRoutes = [
  { pattern: '/products/[slug]', generator: () => ['/products/kritvia-ai', '/products/kritvia-cloud', '/products/kritvia-crm'] },
  { pattern: '/solutions/[slug]', generator: () => ['/solutions/ai-development', '/solutions/web-development', '/solutions/saas-development', '/solutions/cloud-architecture'] },
  { pattern: '/industries/[slug]', generator: () => ['/industries/fintech', '/industries/healthcare', '/industries/ecommerce', '/industries/saas'] },
]

// Helper function to get all routes
export function getAllRoutes(): string[] {
  return [...staticRoutes]
}

// Helper function to get routes by category
export function getRoutesByCategory(category: Route['category']): Route[] {
  return routes.filter(route => route.category === category)
}

// Helper function to find route by path
export function findRouteByPath(path: string): Route | undefined {
  return routes.find(route => route.path === path)
}
`
}

// Generate URL.md content
function generateUrlMd(routes: RouteInfo[]): string {
  const categories: Record<string, RouteInfo[]> = {}
  
  for (const route of routes) {
    if (!categories[route.category]) {
      categories[route.category] = []
    }
    categories[route.category].push(route)
  }
  
  const categoryTitles: Record<string, string> = {
    core: 'Core Pages',
    company: 'Company',
    platform: 'Platform',
    industries: 'Industries',
    solutions: 'Solutions',
    products: 'Products',
    resources: 'Resources',
    legal: 'Legal',
  }
  
  let md = `# Kritvia Website URL Index

> **IMPORTANT RULE:** Whenever a new page is added, removed, or renamed in the \`/app\` directory, the \`URL.md\` file must be updated immediately. Run \`npm run generate-routes\` to auto-update this file.

This document lists every public URL available in the Kritvia website. It acts as the canonical source of truth for the site's routing system.

---

`
  
  for (const [category, categoryRoutes] of Object.entries(categories)) {
    md += `## ${categoryTitles[category] || category}\n\n`
    md += '| Path | Description |\n'
    md += '|------|-------------|\n'
    
    for (const route of categoryRoutes) {
      md += `| \`${route.path}\` | ${route.name} |\n`
    }
    
    md += '\n'
  }
  
  md += `---\n\n`
  md += `## Route Count\n\n`
  md += `- **Total Routes:** ${routes.length}\n\n`
  md += `---\n\n`
  md += `## Auto-Generation\n\n`
  md += `This file is automatically generated from the route structure in \`/app\`. To regenerate:\n\n`
  md += '```bash\n'
  md += 'npm run generate-routes\n'
  md += '```\n'
  
  return md
}

// Main function
function main() {
  console.log('🔍 Scanning /app directory for routes...')
  
  const pages = findAllPages(APP_DIR)
  
  const routes: RouteInfo[] = pages.map(pagePath => {
    const relativePath = path.relative(APP_DIR, pagePath)
    const urlPath = filePathToUrlPath(relativePath)
    const segments = urlPath.split('/').filter(Boolean)
    const name = segments.length > 0 
      ? pathToName(segments[segments.length - 1])
      : 'Home'
    const category = getCategory(relativePath)
    
    return {
      path: urlPath,
      name,
      category,
    }
  })
  
  // Sort routes by path
  routes.sort((a, b) => a.path.localeCompare(b.path))
  
  console.log(`✅ Found ${routes.length} routes`)
  
  // Generate routes.ts
  const routesTsContent = generateRoutesTs(routes)
  fs.writeFileSync(OUTPUT_ROUTES, routesTsContent)
  console.log(`✅ Generated ${OUTPUT_ROUTES}`)
  
  // Generate URL.md
  const urlMdContent = generateUrlMd(routes)
  fs.writeFileSync(OUTPUT_URL_MD, urlMdContent)
  console.log(`✅ Generated ${OUTPUT_URL_MD}`)
  
  console.log('✨ Route generation complete!')
}

main()
